# Generated by Django 5.2.1 on 2025-07-03 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voterecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteRecord',
            new_name='Vote',
        ),
    ]
