# Generated by Django 5.1 on 2025-09-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_voterecord_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            to='polls.choice',
            null=False,  
            ),
        ),

    ]
